TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
#DB += devTektronix_MSO_4104B.db
DATA += devTektronix_MSO58LP.proto

#=======================================
include $(TOP)/configure/RULES
